apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-svc
spec:
  selector:
    matchLabels:
      app: listing-svc
  template:
    metadata:
      labels:
        app: listing-svc
    spec:
      containers:
      - name: listing-svc
        image: trycatchlearn/listing-svc
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: listing-clusterip
spec:
  type: ClusterIP
  selector:
    app: listing-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
